steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/aqueous-nebula-426105-i3/demo-repo/hello-world-image:$COMMIT_SHA'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/aqueous-nebula-426105-i3/demo-repo/hello-world-image:$COMMIT_SHA'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'hello-world-demo'
      - '--image=us-central1-docker.pkg.dev/aqueous-nebula-426105-i3/demo-repo/hello-world-image:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/aqueous-nebula-426105-i3/demo-repo/hello-world-image:$COMMIT_SHA'